### ISSUE TITLE
Add tests for successful http requests

### ISSUE THREAD

**Issue by rjhuijsman** [3rdparty/eventuals#166]
Our unit tests are our one of our most important forms of documentation.

Currently, [our unit tests for `http`](https://github.com/3rdparty/eventuals/blob/main/test/http.cc) suggest that the only expected result of `http::Get` and `http::Post` is an exception; there isn't a single test that doesn't end in an `EXPECT_THROW(...)`.

We should probably test (and thereby helpfully also document) that we can in fact successfully complete a Get or Post request.

CC @benh since I know he cares about tests as documentation.

**Comment by FolMing** [comment]
That's because I am expected to do them whenever I am finished with TCP.
Anyway, good catch and thank you for adding this to our backlog, I could totally forgot about it!

**Comment by benh** [comment]
IIRC @FolMing did write these tests but because they were hitting external services we decided not to commit them until we had a `Socket` class that could be used as a "mock" HTTP server. This is a great example of where our predicted amount of time to create said `Socket` class was perceived to be relatively short so we'd fast follow with the tests, and it definitely hasn't turned out that way! Thanks for the issue @rjhuijsman. We could fill this gap with a simple test fixture that just opens a socket via low-level `socket()` and then we can replace all of that code with the `Socket` functionality in the future. Given that @rjhuijsman will be using this and might find bugs that he wants to fix and contribute back and will want to write tests for those fixes, I think this makes sense. Do you have something like this @FolMing?

**Comment by FolMing** [comment]
Yes, we certainly can do that! Will add as a separate commit to the #115

**Comment by FolMing** [comment]
#167

**Comment by FolMing** [comment]
Tests were added in PR https://github.com/3rdparty/eventuals/pull/179
