### ISSUE TITLE
Skipping builds (for markdown changes) prevents submission

### ISSUE THREAD

**Issue by CodingCanuck** [3rdparty/eventuals#176]
I merged #168 to disable Build and Test checks for changes that only affect markdown files.

That's fine, but it's running afoul of our [branch protection rules](https://github.com/3rdparty/eventuals/settings/branch_protection_rules/22183151) that require a passing result from Build and Test in order to merge a change:
![Screen Shot 2022-01-05 at 11 26 49 AM](https://user-images.githubusercontent.com/19922103/148291862-3ea4d036-c407-4d0f-8982-4b83867e5201.png)
 
Since the build gets skipped it never succeeds, which prevents the submission of markdown-only changes like #170.

This specific issue is covered in this FAQ: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks where the recommended solution is to create a dummy check that only runs on skipped files and emits success: "fix this by creating a generic workflow, with the same name, that will return true in any case"

**Comment by benh** [comment]
Thanks for getting this all buttoned up @CodingCanuck!

I have one request and one suggestion.

Request: can we add a comment into each `nobuild.yml` that explains that the name of the job has to be `"Build and Test"`, e.g., this [line](https://github.com/3rdparty/eventuals/blob/main/.github/workflows/nobuild.yml#L13), since it must match the GitHub branch protection rule? That seems like a nasty little penguin that would be good to document for posterity. In fact, I think adding a link to the FAQ at the top of each `nobuild.yml` would also be helpful explaining why we're creating a "dummy".

Suggestion: I can see putting `nobuild.yml` into `3rdparty/dev-tools` so that it can be shared across repos. Want to add a GitHub issue in `3rdparty/dev-tools`? I think we've also thought about moving `macos.yml`, `ubuntu.yml`, etc, into `3rdparty/dev-tools` and making sure all of our repos have a `bazel build :build` and a `bazel test :test` so that we can have generic workflows.

**Comment by CodingCanuck** [comment]
Addressing both items in https://github.com/3rdparty/dev-tools/pull/20, but if we want to reject that PR then I can send out a bunch of individual PRS to address your request.

**Comment by CodingCanuck** [comment]
This will be rendered obsolete by https://github.com/3rdparty/eventuals/pull/309 which removes our build-skipping logic (similar changes in other repos: https://github.com/reboot-dev/respect/pull/294 and https://github.com/3rdparty/stout/pull/25 )

**Comment by CodingCanuck** [comment]
I think that all of our build-skipping logic has been removed: closing this out.
