### ISSUE TITLE
Best way to store long running eventuals?

### ISSUE THREAD

**Issue by gmthiffault** [3rdparty/eventuals#565]
auto is fine as the return type for eventuals which are created/Start()ed from a context that will continue to exist until the eventual is done. However member variables can't be auto, and you can't have an STL container of auto.

Say I want to create/start an eventual from a callback at "the edge" of my system. A concrete example would be the handler for an RPC in an RPC server. The RPC is supposed to kick off a string of asynchronous actions, and the RPC handler callback doesn't want to block until those actions are done (or else the call wouldn't actually be asynchronous). If you create an eventual to perform the sequence of asynchronous actions, the eventual object has to stay alive until it's finished.

What is the recommended practice in this situation? My current guess would be something like "store the eventual in a list of running eventuals, and have the last step in the asynchronous pipeline delete itself from that list". Do I need to use Task to make the type of the eventual pipelines consistent with each other as well as make the type of the returned eventual predictable/human understandable?

**Comment by benh** [comment]
Yes, `Task` is designed for exactly this. It type-erases the eventual and stores it on the heap so it sticks around.

If you don't want to do heap allocation you might also be able to have a variable that gets defined via `decltype()` which we do [here](https://github.com/3rdparty/eventuals/blob/main/eventuals/concurrent.h#L714-L715). You can make this work as long as the definition of the function "is before" the member declaration, but you sometimes need to jump through hoops here because using functions from within the same class can be tricky because the class isn't fully defined until after it's closing `};`.

Our gRPC implementation uses a `Task` for each service that it's serving, see [here](https://github.com/3rdparty/eventuals/blob/main/eventuals/grpc/server.h#L590-L594). Inside of that task, i.e., the eventual that gets type erased, we use `Concurrent()` which allocates on the heap an eventual for each accepted call so that the call will stick around around until it's finished; see [here](https://github.com/3rdparty/eventuals/blob/main/protoc-gen-eventuals/templates/eventuals.cc.j2#L49-L54).

One combinator that I think would be great to have is something similar to `Concurrent` except with a "fixed size buffer", aka, something like `ConcurrentFixedSize` (have you ever read about the ["LMAX Disruptor"](https://lmax-exchange.github.io/disruptor/disruptor.html)?)

Here's some pseudo code of how this might look:

```cpp
server.Accept()
  >> ConcurrentFixedSize([]() {
          return Map([](int socket) {
            return ...;
          }); 
    })
  >> Loop();
```

The way this would work is as long as there are slots in the buffer then `ConcurrentFixedSize` will recurse into `server.Accept()` for the _next_ item. It is guaranteed that when `server.Accept()` has that item it will be able to find a free slot in the buffer and start an eventual (because we only ask for _next_ when we have a free slot). We won't have to do any heap allocation because we can allocate the buffer ahead of time, and we know the size of each buffer slot is just the size of what ever is returned in the lambda we passed to `ConcurrentFixedSize`.

What's cool about this is that when we've run out of slots the OS will queue up connections, up to the backlog specified in `listen`, and then send errors to connecting clients, aka, we'll get a kind of back pressure! Many libraries greedily accept from the OS and dynamically grow a buffer in user space so from the OS's perspective the application is keeping up even if it is most definitely not. Everything at the end of the day is just buffers. ;-)

You could imagine improving `Concurrent` to do something like this where we don't heap allocate for each item but use something like a `deque` of eventuals internally. But I think it would be even better to be able to have something that never ever dynamically allocates.

Note that this server accept loop that I wrote would still likely be type-erased in a `Task` and thus you'll still do at least one heap allocation (or per accept loop), but that's something that you'll often do only once, at program start up.

**Comment by gmthiffault** [comment]
Awesome, thanks for the reply! I'll play around with Task, thankfully I'm not in a "no dyanmic allocation allowed ever" situation, it's just not ideal. The concurrent stuff seems neat as well, though at the moment we don't have a need for actual concurrency.

**Comment by benh** [comment]
> The concurrent stuff seems neat as well, though at the moment we don't have a need for actual concurrency.

Cool. Just to be extra clear, `Concurrent` provides _concurrency_ not _parallelism_ so it will still only be executed by a single thread (unless you introduced a scheduler for parallelism yourself). 👍

**Comment by gmthiffault** [comment]
Right, yes. Yesterday was a busy day and for some reason my brain did  a weird mapping of parallelism -> concurrency and concurrency -> asynchrony.
